export const inquiryFormSchema = [
  {
    name: 'firstName',
    label: 'First Name',
    type: 'text',
    placeholder: 'First Name',
    validation: { required: true },
  },
  {
    name: 'lastName',
    label: 'Last Name',
    type: 'text',
    placeholder: 'Last Name',
    validation: { required: true },
  },
  {
    name: 'companyName',
    label: 'Company Name',
    type: 'text',
    placeholder: 'Company Name',
    validation: { required: true },
  },
  {
    name: 'title',
    label: 'Company Title',
    type: 'text',
    placeholder: 'Title',
    validation: { required: true },
  },
  {
    name: 'email',
    label: 'Company Email',
    type: 'email',
    placeholder: 'example@example.com',
    validation: { required: true },
  },
  {
    name: 'phoneNumber',
    label: 'Phone Number',
    type: 'text',
    placeholder: 'Phone Number',
    validation: { required: true },
  },
];
//   {
//     name: 'companyType',
//     label: 'Company Type',
//     type: 'dropdown',
//     placeholder: 'Please select',
//     validation: { required: true },
//     options: [
//       'M&A Advisor',
//       'Business Owner / CXO',
//       'Private Equity Fund',
//       'Independent Sponsor',
//       'Single Family Office',
//       'Holding Company',
//       'Search Fund',
//       'Individual Investor',
//       'Lender',
//       'Service Provider',
//       'Student or Recent Graduate',
//       'Other',
//     ],
//   },
//   {
//     name: 'interestInSyncap',
//     label: 'Interest in Syncap',
//     type: 'dropdown',
//     placeholder: 'Please select',
//     validation: { required: true },
//     options: [], // This will be dynamically populated
//   },

//   {
//     name: 'ltmRevenueRange',
//     label: 'LTM Revenue Range',
//     type: 'dropdown',
//     placeholder: 'Please select',
//     validation: { required: true },
//     options: [
//       'Pre-Revenue',
//       '$0-$5M',
//       '$5M-$25M',
//       '$10M-$50M',
//       '$20M-$100M',
//       '$50M-$250M',
//     ],
//     conditions: ['Business Owner / CXO'],
//   },
//   {
//     name: 'ltmNetProfitRange',
//     label: 'LTM Net Profit Range',
//     type: 'dropdown',
//     placeholder: 'Please select',
//     validation: { required: true },
//     options: [
//       'Pre-Profit',
//       '$0-$500K',
//       '$500K-$1M',
//       '$1M-$2M',
//       '$2M-$5M',
//       '$5M+',
//     ],
//     conditions: ['Business Owner / CXO'],
//   },
//   {
//     name: 'searchFundStructure',
//     label: 'Which Structure Best Describes Your Search Fund',
//     type: 'dropdown',
//     placeholder: 'Please select',
//     validation: { required: true },
//     options: [
//       'Traditional Model',
//       'Accelerator or Entrepreneur in Residence Model',
//       'Self Funded Model',
//     ],
//     conditions: ['Search Fund'],
//   },
//   {
//     name: 'role',
//     label: 'Describe Your Role',
//     type: 'dropdown',
//     placeholder: 'Please select',
//     validation: { required: true },
//     options: [
//       'Accountant',
//       'Wealth Manager',
//       'Attorney',
//       'Consultant',
//       'Placement Agent',
//       'Other',
//     ],
//     conditions: ['Service Provider'],
//   },
//   {
//     name: 'country',
//     label: 'Country of Residence',
//     type: 'dropdown',
//     placeholder: 'Please select',
//     validation: { required: true },
//     options: ['United States', 'Canada', 'United Kingdom', 'Other'],
//   },
//   {
//     name: 'howDidYouHearAboutUs',
//     label: 'How Did You Hear About Us?',
//     type: 'text',
//     placeholder: 'Required',
//     validation: { required: true },
//   },
// ];

// export const interestOptions: { [key: string]: string[] } = {
//   'M&A Advisor': [
//     'Sellside M&A',
//     'Buyside M&A',
//     'Raising Capital for an Operating Company',
//     'Raising Capital for a Fund',
//     'Raising Project Financing',
//   ],
//   'Business Owner / CXO': [
//     'Hire an M&A Advisor',
//     'Sell My Company',
//     'Raise Growth Capital',
//     'Make Acquisitions',
//     'Acquire / Invest in Real Estate',
//   ],
//   'Private Equity Fund': [
//     'Acquire / Invest in Companies',
//     'Acquire / Invest in Real Estate',
//     'Sell a Portfolio Company',
//     'Raising Capital for an Operating Company',
//     'Raising Capital for a Fund',
//   ],
//   'Independent Sponsor': [
//     'Acquire / Invest in Companies',
//     'Acquire / Invest in Real Estate',
//     'Sell a Portfolio Company',
//     'Raising Capital for an Operating Company',
//     'Raising Capital for a Fund',
//   ],
//   'Single Family Office': [
//     'Acquire / Invest in Companies',
//     'Acquire / Invest in Real Estate',
//     'Sell a Portfolio Company',
//     'Raising Capital for an Operating Company',
//   ],
//   'Holding Company': [
//     'Acquire / Invest in Companies',
//     'Acquire / Invest in Real Estate',
//     'Sell a Portfolio Company',
//     'Raising Capital for an Operating Company',
//     'Raising Capital for a Fund',
//   ],
//   'Search Fund': [
//     'Acquire / Invest in Companies',
//     'Raising Capital for an Operating Company',
//   ],
//   'Individual Investor': [
//     'Acquire / Invest in Companies',
//     'Acquire / Invest in Real Estate',
//     'Raising Capital for an Operating Company',
//   ],
//   Lender: [
//     'Lend Directly to Businesses',
//     'Lend to Sponsors',
//     'Find Capital Providers',
//   ],
//   'Service Provider': [
//     'Help a Client Exit Their Business',
//     'Help a Corporate Client Raise Capital',
//     'Source Investments for Myself',
//     'Source Investments for a Client',
//     'Find New Clients',
//   ],
//   'Student or Recent Graduate': [],
//   Other: [],
